version: '3.5'

services:
  app:
    image: vergissberlin/phart
    container_name: phart_app
    privileged: false
    depends_on:
      - pigpiod
    links:
      - pigpiod:pigpiod
    environment:
      - PIN_LIGHT_GREEN=4
      - PIN_LIGHT_YELLOW=17
      - PIN_LIGHT_RED=21
      - PIN_INPUT_A=9
      - PIN_INPUT_B=7
      - PIN_INPUT_C=8
      - PIN_INPUT_D=10
      - PIN_OUTPUT_A=22
      - PIN_OUTPUT_B=23
      - PIN_OUTPUT_C=24
      - PIN_OUTPUT_D=25
      - PIN_BUTTON=11
      - PIN_BUZZER=18
      - PIGPIO_ADDR=pigpiod
    volumes:
      - ./data/images:/app/images
    restart: unless-stopped

  pigpiod:
    image: zinen2/alpine-pigpiod:arm32v7 # RPI2: zinen2/alpine-pigpiod:arm32v6
    container_name: phart_pigpiod
    privileged: true
    restart: unless-stopped
